// <auto-generated />
using System;
using MedReability.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedReability.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331124437_AddPatientTrainingPlanDayProgress")]
    partial class AddPatientTrainingPlanDayProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedReability.Domain.Entities.ClinicEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clinics", (string)null);
                });

            modelBuilder.Entity("MedReability.Domain.Entities.DoctorPatientAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ClinicId", "DoctorId", "PatientId")
                        .IsUnique();

                    b.ToTable("doctor_patient_assignments", (string)null);
                });

            modelBuilder.Entity("MedReability.Domain.Entities.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.PrimitiveCollection<string[]>("MediaUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("media_urls");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("Steps")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("steps");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("UserId");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_training_plans", (string)null);
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanDayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rest_day");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientTrainingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_training_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("PatientTrainingPlanId", "DayNumber")
                        .IsUnique();

                    b.ToTable("patient_training_plan_days", (string)null);
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanDayExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("PatientTrainingPlanDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_training_plan_day_id");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("PatientTrainingPlanDayId", "Order")
                        .IsUnique();

                    b.ToTable("patient_training_plan_day_exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_patient_training_plan_day_exercises_prescription", "(repetitions IS NOT NULL AND duration_seconds IS NULL) OR (repetitions IS NULL AND duration_seconds IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanDayProgressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PatientTrainingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_training_plan_id");

                    b.Property<int?>("StateRating")
                        .HasColumnType("integer")
                        .HasColumnName("state_rating");

                    b.HasKey("Id");

                    b.HasIndex("PatientTrainingPlanId");

                    b.HasIndex("PatientId", "PatientTrainingPlanId", "DayNumber")
                        .IsUnique();

                    b.ToTable("patient_training_plan_day_progresses", null, t =>
                        {
                            t.HasCheckConstraint("CK_patient_training_plan_day_progresses_state_rating", "state_rating IS NULL OR (state_rating >= 1 AND state_rating <= 5)");
                        });
                });

            modelBuilder.Entity("MedReability.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patronymic");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId", "Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MedReability.Domain.Entities.DoctorPatientAssignmentEntity", b =>
                {
                    b.HasOne("MedReability.Domain.Entities.ClinicEntity", "ClinicEntity")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedReability.Domain.Entities.UserEntity", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedReability.Domain.Entities.UserEntity", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClinicEntity");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.ExerciseEntity", b =>
                {
                    b.HasOne("MedReability.Domain.Entities.ClinicEntity", "ClinicEntity")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedReability.Domain.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClinicEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanEntity", b =>
                {
                    b.HasOne("MedReability.Domain.Entities.ClinicEntity", "ClinicEntity")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedReability.Domain.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedReability.Domain.Entities.UserEntity", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClinicEntity");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanDayEntity", b =>
                {
                    b.HasOne("MedReability.Domain.Entities.PatientTrainingPlanEntity", "PatientTrainingPlanEntity")
                        .WithMany("Days")
                        .HasForeignKey("PatientTrainingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientTrainingPlanEntity");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanDayExerciseEntity", b =>
                {
                    b.HasOne("MedReability.Domain.Entities.ExerciseEntity", "ExerciseEntity")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedReability.Domain.Entities.PatientTrainingPlanDayEntity", "PatientTrainingPlanDayEntity")
                        .WithMany("Exercises")
                        .HasForeignKey("PatientTrainingPlanDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExerciseEntity");

                    b.Navigation("PatientTrainingPlanDayEntity");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanDayProgressEntity", b =>
                {
                    b.HasOne("MedReability.Domain.Entities.UserEntity", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedReability.Domain.Entities.PatientTrainingPlanEntity", "PatientTrainingPlanEntity")
                        .WithMany()
                        .HasForeignKey("PatientTrainingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PatientTrainingPlanEntity");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("MedReability.Domain.Entities.ClinicEntity", "ClinicEntity")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClinicEntity");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.ClinicEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanEntity", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("MedReability.Domain.Entities.PatientTrainingPlanDayEntity", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
